services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    volumes:
      - ${PGADMIN_DATA}:/var/lib/pgadmin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/misc/ping || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3 