services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3001:3000"
    env_file:
      - .env # Make sure this file exists and contains necessary environment variables (chek .env.example)
    volumes:
      - ${PATH_TO_CONFIG}:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/healthcheck || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
    networks:
      - homepage-net

networks:
  homepage-net:
    driver: bridge
