services:
  siyuan:
    image: b3log/siyuan
    container_name: siyuan
    command: [ "--workspace=/siyuan/workspace", "--accessAuthCode=${SIYUAN_ACCESS_CODE}" ]
    ports:
      - "${SIYUAN_PORT:-6806}:6806"
    volumes:
      - "${SIYUAN_DATA_DIR}:/siyuan/workspace"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
